

build:
	mvn package

client: 
	java -cp target/printer-1.0-SNAPSHOT.jar dtu.client.Client

server: 
	java -cp lib/sqlite-jdbc-3.36.0.3.jar:target/printer-1.0-SNAPSHOT.jar dtu.server.Server

clean:
	mvn clean


